#
# This file is a part of Chimera
#
# Copyright © 2021
# Michael Wyatt, All rights reserved.
#
# This file contains code from:
# Michael Wyatt
#
# Chimera is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Chimera is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

BUILD_DIR=$(PREFIX_DIR)/sys/build

# Defines __DEBUG so we can print to serial console, eventually we will transition to an if statement
export CXXFLAGS+=-D __DEBUG

## Standard, cross platform flags

# In a nutshell, we are telling not to include any standard libraries as we are
# running in a freestanding environment. This also means that we do not have
# exception handling nor do we have the ctti.o files to link against. This is
# subject to change, but without those function constructors are not called.
#
# It is important to note the use of the '+=' assignment operator: without it
# we would override all of the existing flags we set in other .mk includes as
# well as anything passed in from the terminal.
CXXFLAGS+=	-ffreestanding -O2 -Wall -Wextra -fno-exceptions -fno-rtti \
			-DTARGET_ARCH=$(TARGET_ARCH) -std=c++20
LDFLAGS+=	-nostdlib

# Tell clang where our headers reside
INCLUDES=-I $(PREFIX_DIR)/sys/kern -I $(PREFIX_DIR)/sys/kern/include \
			-I $(PREFIX_DIR)/sys/kern/lib/include

## Arch specific flags

# i386
ifeq ($(TARGET_ARCH),i386)
	ASFLAGS+=	-march=i686 --32
	CXXFLAGS+=	-march=i386 -target i386-none-elf
	LDFLAGS+=	-melf_i386 -nostdlib
	
	# Tell ld which linker script to use
	LDSCRIPT=	$(PREFIX_DIR)/sys/kern/arch/i386/i386.ld
endif