#
# This file is a part of <OS>
#
# Copyright (c) 2021
# Michael Wyatt, All rights reserved.
#
# This file contains code from:
# Michael Wyatt
#
# <OS> is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# <OS> is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

include $(PREFIX_DIR)/usr/lib/mk/sys.mk
include $(PREFIX_DIR)/Makefile.conf
include $(PREFIX_DIR)/usr/lib/mk/generic.mk

CXXFLAGS+=	-march=$(TARGET_ARCH) -target $(TARGET_TRIPLET)
ASFLAGS+=	-melf_i386 -nostdlib